In [8]:
import pandas as pd

In [9]:
df1 = pd.read_excel("ACE_0320.xlsx")
df1.head()

,Sr.No.,Accord Code,Company Name,FR_ROA (%)4,FR_ROE (%)4,FR_ROCE (%)4,FR_Asset Turnover(x)4,FR_Year End4,FR_Adjusted PE (x)4,FR_Price / Book Value(x)4,FR_Dividend Yield(%)4,FR_EV/EBITDA(x)4,FR_Year End4.1,CONS_FR_1,CONS_FR_2,CONS_FR_3,CONS_FR_4,CONS_FR_5,CONS_FR_6
0,1,207635.0,20 Microns Ltd.,5.435195,13.610332,18.907800,1.193281,202003.0,3.760279,0.482881,2.334630,2.936048,202003.0,C,C,C,C,C,C
1,2,126921.0,21st Century Management Services Ltd.,-77.822654,-93.811406,-83.684657,0.000000,202003.0,0.000000,0.717084,0.000000,-0.309694,202003.0,C,C,C,C,C,C
2,3,228974.0,360 One Wam Ltd.,1.765841,6.857861,7.561351,0.129037,202003.0,42.763386,2.900420,2.026035,19.615545,202003.0,C,C,C,C,C,C
3,4,132067.0,3B Blackbio Dx Ltd.,18.940620,28.152488,32.291219,0.711441,202003.0,7.079706,1.692477,0.964852,4.441286,202003.0,C,C,C,C,C,C
4,5,132628.0,3I Infotech Ltd.,4.515416,20.010885,13.962539,0.463504,202003.0,3.157139,0.593745,0.000000,5.243403,202003.0,C,C,C,C,C,C

In [10]:
df2 = pd.read_excel("TRENDLYNE_230425.xlsx")
df2.head()

,Stock Name,NSE Code,BSE Code,Stock Code,ISIN,Industry Name,Current Price,Current Price.1,Market Capitalization,PE TTM Price to Earnings,...,Sector Return on Equity ROE,Industry Return on Equity ROE,RoA Annual %,Sector Return on Assets,Industry Return on Assets,Piotroski Score,sector_name,Industry Name.1,Latest financial result,Result Announced Date
0,20 Microns Ltd.,20MICRONS,533022.0,20MICRONS,INE144J01027,Coal & Mining,227.25,227.25,801.89,13.19,...,23.96,38.63,9.50,10.88,17.60,7.0,Metals & Mining,Coal & Mining,2024-12-31,2025-01-22
1,360 ONE Gold ETF,GOLD360,544375.0,GOLD360,INF579M01BB5,Others,95.45,95.45,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Others,Others,NaT,NaT
2,360 ONE Silver ETF,SILVER360,544389.0,SILVER360,INF579M01BC3,Others,99.20,99.20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Others,Others,NaT,NaT
3,360 One Wam Ltd.,360ONE,542772.0,360ONE,INE466L01038,Capital Markets,1057.00,1057.00,41613.87,41.27,...,17.25,23.88,5.31,2.86,8.70,3.0,Banking and Finance,Capital Markets,2024-12-31,2025-04-23
4,3B BlackBio Dx Ltd.,NaN,532067.0,3BBLACKBIO,INE994E01018,Agrochemicals,1784.05,1784.05,1531.20,31.87,...,14.53,17.06,12.93,9.90,12.59,7.0,Chemicals & Petrochemicals,Agrochemicals,2024-12-31,2025-02-13

In [23]:
merged_df = pd.merge(df1, df2, left_on='Company Name', right_on='Stock Name')
merged_df.tail()

,Sr.No.,Accord Code,Company Name,FR_ROA (%)4,FR_ROE (%)4,FR_ROCE (%)4,FR_Asset Turnover(x)4,FR_Year End4,FR_Adjusted PE (x)4,FR_Price / Book Value(x)4,...,Sector Return on Equity ROE,Industry Return on Equity ROE,RoA Annual %,Sector Return on Assets,Industry Return on Assets,Piotroski Score,sector_name,Industry Name.1,Latest financial result,Result Announced Date
3904,4546,103641.0,Zodiac Ventures Ltd.,0.030863,0.468046,18.869324,0.001315,202003.0,0.000000,4.733551,...,11.62,18.43,0.27,5.38,9.01,3.0,Commercial Services & Supplies,Consulting Services,2024-12-31,2025-02-14
3905,4549,229943.0,Zuari Agro Chemicals Ltd.,-10.890195,-114.471789,-5.617654,0.651834,202003.0,0.000000,0.764885,...,12.69,12.69,2.07,7.14,7.14,6.0,Fertilizers,Fertilizers,2024-12-31,2025-02-06
3906,4550,100780.0,Zuari Industries Ltd.,-9.678643,-23.641417,-4.878987,0.188525,202003.0,0.000000,0.069512,...,19.70,13.89,9.52,14.51,7.96,6.0,Food Beverages & Tobacco,Sugar,2024-12-31,2025-02-13
3907,4551,132321.0,Zydus Lifesciences Ltd.,5.184965,11.324535,10.022722,0.628631,202003.0,23.245897,2.636067,...,16.90,17.11,13.18,11.67,11.81,8.0,Pharmaceuticals & Biotechnology,Pharmaceuticals,2024-12-31,2025-02-05
3908,4552,131335.0,Zydus Wellness Ltd.,2.618524,4.139659,5.257649,0.356801,202003.0,52.769482,2.161005,...,42.17,75.29,4.34,19.26,26.66,7.0,FMCG,Packaged Foods,2024-12-31,2025-02-04

In [ ]:
import os
import pandas as pd

folder_path = "C:/Users/meets/nse-benny/eod2/src/eod2_data/daily"  
target_date = "2020-03-31"
close_prices = {}

for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)

        df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
        match = df[df['Date'] == target_date]

        file_key = file.replace(".csv", "").upper()
        if not match.empty:
            close_prices[file_key] = match.iloc[0]['Close']
        else:
            close_prices[file_key] = None

print(close_prices)

df = pd.DataFrame(list(close_prices.items()), columns=['STOCKNAME', 'PRICE0320'])
print(df.count())
df = df.dropna()
df.tail()

{'20MICRONS': 25.55, '21STCENMGM': 10.8, '360ONE': 251.45, '3IINFOLTD': None, '3MINDIA': 18827.95, '3PLAND': 3.55, '5PAISA': 113.15, '63MOONS': 46.05, 'A2ZINFRA': 3.15, 'AAATECH': None, 'AADHARHFC': None, 'AAKASH': None, 'AAREYDRUGS': None, 'AARON': None, 'AARTECH': None, 'AARTIDRUGS': 125.6, 'AARTIIND': 383.4, 'AARTIPHARM': None, 'AARTISURF': None, 'AARVEEDEN': 7.95, 'AARVI': 21.2, 'AATMAJ_SME': None, 'AAVAS': 1188.85, 'ABAN': 14.0, 'ABB': 935.4, 'ABBOTINDIA': 15451.1, 'ABCAPITAL': 42.15, 'ABCOTS_SME': None, 'ABDL': None, 'ABFRL': 152.9, 'ABGSEC': None, 'ABHAPOWER_SME': None, 'ABINFRA': 9.05, 'ABMINTLLTD': None, 'ABREL': 296.1, 'ABSLAMC': None, 'ABSLBANETF': 235.0, 'ABSLLIQUID': None, 'ABSLNN50ET': 228.0, 'ABSLPSE': None, 'ABSMARINE_SME': None, 'ACC': 968.5, 'ACCELYA': 853.0, 'ACCENTMIC_SME': None, 'ACCORD_SME': None, 'ACCURACY': 1.35, 'ACE': 34.25, 'ACEINTEG': None, 'ACI': None, 'ACL': None, 'ACLGATI': 48.95, 'ACMESOLAR': None, 'ADANIENSOL': 189.05, 'ADANIENT': 137.6, 'ADANIGREEN': 153.25, 'ADANIPORTS': 251.3, 'ADANIPOWER': 27.75, 'ADFFOODS': 34.0, 'ADL': None, 'ADORWELD': 185.4, 'ADROITINFO': 5.85, 'ADSL': 12.8, 'ADVANIHOTR': 15.05, 'ADVENZYMES': 142.5, 'AEGISLOG': 139.45, 'AEROFLEX': None, 'AERON_SME': None, 'AESTHETIK_SME': None, 'AETHER': None, 'AFCONS': None, 'AFFLE': 201.1, 'AFFORDABLE': None, 'AFIL': None, 'AGARIND': 44.45, 'AGARWALEYE': None, 'AGARWALFT_SME': None, 'AGARWALTUF_SME': None, 'AGI': 40.35, 'AGIIL': None, 'AGNI_SME': None, 'AGRITECH': 19.85, 'AGROPHOS': 5.7, 'AGSTRA': None, 'AGUL_SME': None, 'AHIMSA_SME': None, 'AHL': None, 'AHLADA': 45.65, 'AHLEAST': 86.0, 'AHLUCONT': 171.6, 'AIAENG': 1393.25, 'AIIL': None, 'AILIMITED_SME': None, 'AIMTRON_SME': None, 'AIRAN': 9.45, 'AIROLAM': None, 'AISL_SME': None, 'AJANTPHARM': 910.85, 'AJAXENGG': None, 'AJMERA': 64.7, 'AJOONI': None, 'AKANKSHA_SME': None, 'AKASH': None, 'AKG': None, 'AKI': None, 'AKIKO_SME': None, 'AKSHAR': None, 'AKSHARCHEM': 151.7, 'AKSHOPTFBR': 3.0, 'AKUMS': None, 'AKZOINDIA': 2213.05, 'ALANKIT': 10.7, 'ALBERTDAVD': 318.55, 'ALEMBICLTD': 35.35, 'ALICON': 176.1, 'ALIVUS': None, 'ALKALI': 25.1, 'ALKEM': 2325.85, 'ALKYLAMINE': 481.3, 'ALLCARGO': 14.6, 'ALLDIGI': 115.5, 'ALLETEC_SME': None, 'ALMONDZ': None, 'ALOKINDS': 3.95, 'ALPA': 13.85, 'ALPEXSOLAR_SME': None, 'ALPHA': None, 'ALPHAETF': None, 'ALPHAGEO': 124.85, 'ALPL30IETF': None, 'ALPSINDUS': 0.75, 'ALUWIND_SME': None, 'AMBANIORGO_SME': None, 'AMBER': 1230.45, 'AMBEY_SME': None, 'AMBICAAGAR': None, 'AMBIKCO': 527.95, 'AMBUJACEM': 155.7, 'AMDIND': 10.55, 'AMEYA_SME': None, 'AMIABLE_SME': None, 'AMIORG': None, 'AMJLAND': 14.5, 'AMJUMBO_SME': None, 'AMNPLST': None, 'AMRUTANJAN': 329.95, 'ANANDRATHI': None, 'ANANTRAJ': 19.8, 'ANDHRAPAP': 28.3, 'ANDHRSUGAR': 35.4, 'ANGELONE': None, 'ANIKINDS': 6.55, 'ANKITMETAL': 0.4, 'ANLON_SME': None, 'ANMOL': None, 'ANNAPURNA_SME': None, 'ANSALAPI': 3.55, 'ANTGRAPHIC': None, 'ANUHPHR': None, 'ANUP': 162.95, 'ANURAS': None, 'ANYA_SME': None, 'AONETOTAL': None, 'APARINDS': 288.2, 'APCL': 94.35, 'APCOTEXIND': 77.35, 'APEX': 168.55, 'APEXECO_SME': None, 'APLAPOLLO': 124.7, 'APLLTD': 534.25, 'APOLLO': 4.5, 'APOLLOHOSP': 1139.05, 'APOLLOPIPE': 81.6, 'APOLLOTYRE': 79.4, 'APOLSINHOT': 392.0, 'APRAMEYA_SME': None, 'APS_SME': None, 'APTECHT': 59.65, 'APTUS': None, 'ARABIAN_SME': None, 'ARCHIDPLY': 15.4, 'ARCHIES': 8.8, 'ARE&M': 478.05, 'ARENTERP': None, 'ARHAM_SME': None, 'ARIES': 40.0, 'ARIHANTACA_SME': None, 'ARIHANTCAP': None, 'ARIHANTSUP': 21.0, 'ARISTO_SME': None, 'ARKADE': None, 'ARMANFIN': 414.5, 'AROGRANITE': 18.8, 'ARROWGREEN': 33.6, 'ARSHIYA': 6.8, 'ARSSINFRA': 10.0, 'ARTEMISMED': 13.7, 'ARTNIRMAN': None, 'ARVEE': None, 'ARVIND': 19.65, 'ARVINDFASN': 146.55, 'ARVINDPORT_SME': None, 'ARVSMART': 67.55, 'ASAHIINDIA': 156.15, 'ASAHISONG': 73.5, 'ASAL': 13.0, 'ASALCBR': 157.9, 'ASCOM_SME': None, 'ASHALOG_SME': None, 'ASHAPURMIN': 20.45, 'ASHIANA': 49.8, 'ASHIMASYN': 3.2, 'ASHOKA': 41.35, 'ASHOKAMET': None, 'ASHOKLEY': 43.05, 'ASIANENE': None, 'ASIANHOTNR': 68.75, 'ASIANPAINT': 1666.5, 'ASIANTILES': 161.85, 'ASKAUTOLTD': None, 'ASLIND_SME': None, 'ASMS': None, 'ASPINWALL': 86.5, 'ASPIRE_SME': None, 'ASTEC': 388.3, 'ASTERDM': 95.15, 'ASTRAL': 527.0, 'ASTRAMICRO': 51.9, 'ASTRAZEN': 2403.85, 'ASTRON': 26.95, 'ATALREAL': None, 'ATAM': None, 'ATFL': 382.3, 'ATGL': 86.35, 'ATL': None, 'ATLANTAA': 2.7, 'ATLASCYCLE': None, 'ATMASTCO_SME': None, 'ATUL': 3988.45, 'ATULAUTO': 139.35, 'AUBANK': 252.7, 'AURDIS_SME': None, 'AURIONPRO': 20.25, 'AUROIMPEX_SME': None, 'AUROPHARMA': 413.15, 'AURUM': 254.55, 'AUSL_SME': None, 'AUSOMENT': 26.35, 'AUTOAXLES': 384.05, 'AUTOBEES': None, 'AUTOIETF': None, 'AUTOIND': 9.75, 'AVADHSUGAR': 118.15, 'AVALON': None, 'AVANTEL': None, 'AVANTIFEED': 294.25, 'AVG': None, 'AVIANSH_SME': None, 'AVL': None, 'AVONMORE': None, 'AVPINFRA_SME': None, 'AVROIND': None, 'AVSL_SME': None, 'AVTNPL': 23.65, 'AWFIS': None, 'AWHCL': None, 'AWL': None, 'AXISBANK': 379.0, 'AXISBNKETF': None, 'AXISBPSETF': None, 'AXISCADES': 28.15, 'AXISCETF': None, 'AXISGOLD': 3852.8, 'AXISHCETF': None, 'AXISILVER': None, 'AXISNIFTY': 1056.0, 'AXISTECETF': None, 'AXITA': None, 'AXSENSEX': None, 'AYMSYNTEX': 15.75, 'AZAD': None, 'BABAFP_SME': None, 'BAFNAPH': 13.3, 'BAGFILMS': 1.8, 'BAHETI_SME': None, 'BAIDFIN': None, 'BAJAJ-AUTO': 2022.35, 'BAJAJCON': 132.45, 'BAJAJELEC': 268.45, 'BAJAJFINSV': 459.1, 'BAJAJHCARE': None, 'BAJAJHFL': None, 'BAJAJHIND': 2.65, 'BAJAJHLDNG': 1798.55, 'BAJAJINDEF': None, 'BAJEL': None, 'BAJFINANCE': 2215.8, 'BALAJEE': None, 'BALAJIPHOS_SME': None, 'BALAJITELE': 37.75, 'BALAMINES': 251.6, 'BALAXI': 14.8, 'BALCO_SME': None, 'BALKRISHNA': 7.8, 'BALKRISIND': 791.65, 'BALMLAWRIE': 79.45, 'BALPHARMA': 31.9, 'BALRAMCHIN': 104.05, 'BALUFORGE': None, 'BANARBEADS': 29.45, 'BANARISUG': 867.7, 'BANCOINDIA': 32.5, 'BANDHANBNK': 203.75, 'BANG': 11.6, 'BANKA': None, 'BANKBARODA': 53.55, 'BANKBEES': 194.57, 'BANKBETF': None, 'BANKETF': None, 'BANKETFADD': None, 'BANKIETF': 192.75, 'BANKINDIA': 32.25, 'BANKNIFTY1': 193.46, 'BANKPSU': None, 'BANSALWIRE': None, 'BANSWRAS': 36.4, 'BARBEQUE': None, 'BARFLEX_SME': None, 'BASF': 1125.25, 'BASILIC_SME': None, 'BASML': 34.7, 'BATAINDIA': 1231.1, 'BAWEJA_SME': None, 'BAYERCROP': 3455.95, 'BBETF0432': None, 'BBL': 284.75, 'BBNPNBETF': None, 'BBNPPGOLD': None, 'BBOX': 45.35, 'BBTC': 732.5, 'BBTCL': None, 'BCG': 1.5, 'BCLIND': None, 'BCONCEPTS': None, 'BDL': 92.6, 'BEACON_SME': None, 'BEARDSELL': 6.8, 'BECTORFOOD': None, 'BEDMUTHA': 13.15, 'BEL': 24.8, 'BEML': 451.65, 'BEPL': 19.25, 'BERGEPAINT': 414.95, 'BESTAGRO': None, 'BETA_SME': 40.0, 'BEWLTD_SME': None, 'BFINVEST': 226.8, 'BFSI': None, 'BFUTILITIE': 144.2, 'BGLOBAL': None, 'BGRENERGY': 20.95, 'BHAGCHEM': None, 'BHAGERIA': 75.65, 'BHAGYANGR': 14.3, 'BHANDARI': 0.75, 'BHARATFORG': 234.95, 'BHARATGEAR': 17.0, 'BHARATRAS': 5159.6, 'BHARATWIRE': 11.2, 'BHARTIARTL': 440.9, 'BHARTIHEXA': None, 'BHEL': 20.8, 'BIGBLOC': 2.85, 'BIKAJI': None, 'BIKEWO_SME': None, 'BIL': 73.15, 'BINANIIND': None, 'BIOCON': 270.55, 'BIOFILCHEM': 7.5, 'BIRDYS_SME': None, 'BIRLACABLE': 32.5, 'BIRLACORPN': 415.05, 'BIRLAMONEY': 19.3, 'BKMINDST': 0.4, 'BLACKBUCK': None, 'BLAL': None, 'BLBLIMITED': 3.2, 'BLISSGVS': 100.75, 'BLKASHYAP': 4.7, 'BLS': 7.3, 'BLSE': None, 'BLUECHIP': 0.1, 'BLUECOAST': 4.2, 'BLUEDART': 2199.05, 'BLUEJET': None, 'BLUEPEBBLE_SME': None, 'BLUESTARCO': 229.7, 'BMETRICS_SME': None, 'BODALCHEM': 42.4, 'BOHRAIND': None, 'BOMDYEING': 45.8, 'BOROLTD': None, 'BORORENEW': 37.25, 'BOROSCI': None, 'BOSCHLTD': 9395.55, 'BOSS_SME': None, 'BPCL': 158.45, 'BPL': 11.05, 'BRACEPORT_SME': None, 'BRIGADE': 130.15, 'BRIGHT_SME': None, 'BRITANNIA': 2688.95, 'BRNL': 33.05, 'BROOKS': 15.25, 'BSE': 98.95, 'BSE500IETF': 114.86, 'BSHSL': 10.8, 'BSL': 18.6, 'BSLGOLDETF': 4039.6, 'BSLNIFTY': 101.9, 'BSLSENETFG': None, 'BSOFT': 61.0, 'BTML': None, 'BULKCORP_SME': None, 'BURNPUR': 0.7, 'BUTTERFLY': 95.75, 'BVCL': 7.55, 'BYKE': 8.8, 'C2C_SME': None, 'CADSYS_SME': None, 'CALSOFT': 7.75, 'CAMLINFINE': 39.0, 'CAMPUS': None, 'CAMS': None, 'CANARYS_SME': None, 'CANBK': 18.1, 'CANFINHOME': 279.05, 'CANTABIL': 40.25, 'CAPACITE': 73.4, 'CAPITALSFB': None, 'CAPLIPOINT': 282.4, 'CAPTRUST': 50.7, 'CARBORUNIV': 222.0, 'CAREERP': 122.9, 'CARERATING': 327.35, 'CARRARO': None, 'CARTRADE': None, 'CARYSIL': None, 'CASTROLIND': 99.45, 'CBAZAAR_SME': None, 'CCCL': None, 'CCHHL': 1.8, 'CCL': 177.4, 'CDSL': 107.2, 'CEATLTD': 792.95, 'CEIGALL': None, 'CELEBRITY': 3.8, 'CELLECOR_SME': None, 'CELLO': None, 'CELLPOINT_SME': None, 'CENTENKA': 119.0, 'CENTEXT': 1.7, 'CENTRALBK': 12.25, 'CENTRUM': 9.05, 'CENTUM': 252.85, 'CENTURYPLY': 110.95, 'CERA': 2311.45, 'CEREBRAINT': 17.55, 'CESC': 40.85, 'CEWATER': None, 'CGCL': 42.7, 'CGPOWER': 5.05, 'CGRAPHICS_SME': None, 'CHALET': 205.15, 'CHAMBLFERT': 108.45, 'CHAMUNDA_SME': None, 'CHANDAN_SME': None, 'CHAVDA_SME': None, 'CHEMBOND': 146.8, 'CHEMCON': None, 'CHEMFAB': 101.2, 'CHEMPLASTS': None, 'CHENNPETRO': 60.55, 'CHETANA_SME': None, 'CHEVIOT': None, 'CHOICEIN': None, 'CHOLAFIN': 152.85, 'CHOLAHLDNG': 290.0, 'CIEINDIA': 68.75, 'CIGNITITEC': 189.05, 'CINELINE': 18.75, 'CINEVISTA': 4.9, 'CIPLA': 422.85, 'CLEAN': None, 'CLEDUCATE': 7.8, 'CLOUD_SME': None, 'CLSEL': None, 'CLSL_SME': None, 'CMICABLES': 19.95, 'CMMIPL_SME': None, 'CMNL_SME': None, 'CMRSL_SME': None, 'CMSINFO': None, 'COALINDIA': 140.05, 'COASTCORP': None, 'COCHINSHIP': 133.2, 'COFFEEDAY': None, 'COFORGE': 1147.75, 'COLPAL': 1252.7, 'COMMITTED_SME': None, 'COMMOIETF': None, 'COMPINFO': 8.0, 'COMPUSOFT': 3.6, 'COMSYN': None, 'CONCOR': 331.65, 'CONCORDBIO': None, 'CONFIPET': 14.75, 'CONS': None, 'CONSOFINVT': 22.4, 'CONSUMBEES': 47.33, 'CONSUMER': None, 'CONSUMIETF': None, 'CONTI_SME': None, 'CONTROLPR': 186.25, 'COOLCAPS_SME': None, 'CORALFINAC': 12.95, 'CORDSCABLE': 24.5, 'COROMANDEL': 546.2, 'COSMOFIRST': 138.7, 'COUNCODOS': 0.75, 'CPSEETF': 16.06, 'CPS_SME': None, 'CRAFTSMAN': None, 'CRAYONS_SME': None, 'CREATIVE': 77.95, 'CREATIVEYE': 1.5, 'CREDITACC': 337.35, 'CREST': 52.4, 'CRISIL': 1254.3, 'CROMPTON': 208.8, 'CROWN': 42.0, 'CSBBANK': 118.05, 'CSLFINANCE': None, 'CTE': 13.95, 'CUB': 129.05, 'CUBEXTUB': 8.55, 'CUMMINSIND': 326.7, 'CUPID': 7.05, 'CYBERMEDIA': None, 'CYBERTECH': 28.5, 'CYIENT': 229.3, 'CYIENTDLM': None, 'DABUR': 450.05, 'DALBHARAT': 490.6, 'DALMIASUG': 48.3, 'DAMCAPITAL': None, 'DAMODARIND': 18.0, 'DANGEE': None, 'DANISH_SME': None, 'DATAMATICS': 41.05, 'DATAPATTNS': None, 'DAVANGERE': None, 'DBCORP': 79.6, 'DBEIL': None, 'DBL': 211.05, 'DBOL': None, 'DBREALTY': 5.05, 'DBSTOCKBRO': 7.0, 'DCAL': 53.35, 'DCBBANK': 94.8, 'DCG_SME': None, 'DCI': None, 'DCM': 13.4, 'DCMFINSERV': 0.4, 'DCMNVL': 23.9, 'DCMSHRIRAM': 215.2, 'DCMSRIND': None, 'DCW': 7.25, 'DCXINDIA': None, 'DDEVPLSTIK': None, 'DECCANCE': 196.15, 'DECCANTRAN_SME': None, 'DEEDEV': None, 'DEEM_SME': None, 'DEEPAKFERT': 75.15, 'DEEPAKNTR': 385.05, 'DEEPENR': 53.3, 'DEEPINDS': None, 'DELAPLEX_SME': None, 'DELHIVERY': None, 'DELPHIFX': 369.95, 'DELTACORP': 65.35, 'DELTAMAGNT': 27.0, 'DELTIC_SME': None, 'DEN': 30.3, 'DENEERS_SME': None, 'DENORA': 133.8, 'DENTA': None, 'DENTALKART_SME': None, 'DESTINY_SME': None, 'DEVIT': None, 'DEVYANI': None, 'DGCONTENT': 4.2, 'DHAMPURSUG': 82.35, 'DHANBANK': 8.05, 'DHANI': 107.7, 'DHANLAXMI_SME': None, 'DHANUKA': 325.2, 'DHARIWAL_SME': None, 'DHARMAJ': None, 'DHRUV': None, 'DHTL_SME': None, 'DHUNINV': 122.35, 'DIACABS': None, 'DIAMINESQ': None, 'DIAMONDYD': 497.2, 'DICIND': 271.35, 'DIFFNKG': None, 'DIGIDRIVE': None, 'DIGIKORE_SME': None, 'DIGISPICE': 2.9, 'DIGJAMLMTD': None, 'DIL': 2.25, 'DISHTV': 4.05, 'DIVGIITTS': None, 'DIVISLAB': 1989.05, 'DIVOPPBEES': 24.97, 'DIVYADHAN_SME': None, 'DIXON': 715.95, 'DJML': None, 'DKEGL_SME': None, 'DLF': 137.45, 'DLINKINDIA': 61.0, 'DMART': 2187.5, 'DMCC': None, 'DNAMEDIA': 0.3, 'DODLA': None, 'DOLATALGO': 35.25, 'DOLLAR': 109.6, 'DOLLEX_SME': None, 'DOLPHIN': None, 'DOMS': None, 'DONEAR': 20.85, 'DPABHUSHAN': None, 'DPEL_SME': None, 'DPSCLTD': 6.15, 'DPWIRES': 45.3, 'DRCSYSTEMS': None, 'DREAMFOLKS': None, 'DREDGECORP': 145.45, 'DRL_SME': None, 'DRONE_SME': None, 'DRREDDY': 624.15, 'DRSDILIP_SME': 75.05, 'DSSL': 14.95, 'DTIL': 74.6, 'DTL_SME': None, 'DUCOL_SME': None, 'DUCON': 2.25, 'DUGLOBAL_SME': None, 'DURLAX_SME': None, 'DVL': 46.35, 'DWARKESH': 16.55, 'DYCL': None, 'DYNAMATECH': 463.55, 'DYNAMIC_SME': None, 'DYNPRO': 115.45, 'E2E': None, 'EASEMYTRIP': None, 'EASTSILK': 0.7, 'EBANKNIFTY': None, 'EBBETF0425': None, 'EBBETF0430': 1041.38, 'EBBETF0431': None, 'EBBETF0433': None, 'ECAPINSURE': None, 'ECLERX': 243.6, 'ECOSMOBLTY': None, 'EDELWEISS': 38.4, 'EDUCOMP': 0.95, 'EFACTOR_SME': None, 'EFFWA_SME': None, 'EFORCE_SME': None, 'EGOLD': None, 'EICHERMOT': 1309.6, 'EIDPARRY': 139.05, 'EIEL': None, 'EIFFL': None, 'EIHAHOTELS': 104.3, 'EIHOTEL': 65.8, 'EIMCOELECO': 191.65, 'EKC': 10.9, 'ELDEHSG': None, 'ELECON': 9.45, 'ELECTCAST': 9.3, 'ELECTHERM': 86.75, 'ELGIEQUIP': 56.0, 'ELGIRUBCO': 11.1, 'ELGNZ_SME': None, 'ELIN': None, 'EMAMILTD': 169.95, 'EMAMIPAP': 49.5, 'EMAMIREAL': 28.05, 'EMAPARTNER_SME': None, 'EMBDL': 40.85, 'EMCURE': None, 'EMIL': None, 'EMKAY': 25.75, 'EMKAYTOOLS_SME': None, 'EMMBI': 43.75, 'EMMIL_SME': None, 'EMSLIMITED': None, 'EMUDHRA': None, 'EMULTIMQ': None, 'ENDURANCE': 601.1, 'ENERGYDEV': 4.3, 'ENFUSE_SME': None, 'ENGINERSIN': 60.05, 'ENIL': 119.95, 'ENSER_SME': None, 'ENTERO': None, 'ENVIRO_SME': None, 'EPACK': None, 'EPIGRAL': None, 'EPL': 155.1, 'EQUAL200': None, 'EQUAL50ADD': None, 'EQUIPPP': None, 'EQUITASBNK': None, 'ERIS': 368.9, 'EROSMEDIA': 8.5, 'ESABINDIA': 1086.1, 'ESAFSFB': None, 'ESCONET_SME': None, 'ESCORTS': 662.6, 'ESFL_SME': None, 'ESG': None, 'ESILVER': None, 'ESPRIT_SME': None, 'ESSARSHPNG': 5.2, 'ESSENTIA': 0.1, 'ESTER': 24.05, 'ETHOSLTD': None, 'ETML_SME': None, 'EUREKAFORB': None, 'EUROBOND_SME': None, 'EUROTEXIND': 8.05, 'EVEREADY': 50.45, 'EVERESTIND': 132.35, 'EVINDIA': None, 'EXCEL': 0.05, 'EXCELINDUS': 446.85, 'EXCELLENT_SME': None, 'EXICOM': None, 'EXIDEIND': 131.6, 'EXPLEOSOL': 143.55, 'EXXARO': None, 'FACT': 32.4, 'FAIRCHEMOR': None, 'FALCONTECH_SME': None, 'FAZE3Q': None, 'FCL': 14.7, 'FCONSUMER': 7.3, 'FCSSOFT': 0.15, 'FDC': 194.95, 'FEDERALBNK': 41.05, 'FEDFINA': None, 'FEL': 8.65, 'FELDVR': 9.45, 'FELIX_SME': None, 'FIBERWEB': None, 'FIDEL_SME': None, 'FIEMIND': 126.55, 'FILATEX': 8.9, 'FILATFASH': None, 'FINCABLES': 203.75, 'FINEORG': 1906.05, 'FINIETF': None, 'FINOPB': None, 'FINPIPE': 78.55, 'FIRSTCRY': None, 'FIVESTAR': None, 'FLAIR': None, 'FLEXITUFF': 3.25, 'FLFL': 117.95, 'FLUOROCHEM': 286.0, 'FMCGIETF': None, 'FMGOETZE': 322.55, 'FMNL': 8.6, 'FOCE_SME': None, 'FOCUS': 4.1, 'FONEBOX_SME': None, 'FOODSIN': None, 'FORCAS_SME': None, 'FORCEMOT': 733.65, 'FORGEAUTO_SME': None, 'FORTIS': 126.15, 'FOSECOIND': 901.85, 'FRESHARA_SME': None, 'FRETAIL': 78.3, 'FROG_SME': None, 'FSC': 104.55, 'FSL': 27.45, 'FUSION': None, 'GABRIEL': 53.3, 'GAEL': 26.2, 'GAIL': 51.05, 'GAJANAND_SME': None, 'GALAPREC': None, 'GALAXYSURF': 1178.45, 'GALLANTT': 19.5, 'GANDHAR': None, 'GANDHITUBE': 189.15, 'GANECOS': 164.4, 'GANESHBE': None, 'GANESHHOUC': 17.75, 'GANESHIN_SME': None, 'GANGAFORGE': None, 'GANGESSECU': 21.6, 'GANGOTRI': None, 'GARFIBRES': 214.85, 'GARUDA': None, 'GATECH': 0.35, 'GATECHDVR': 0.2, 'GATEWAY': None, 'GAYAHWS': 0.25, 'GAYAPROJ': 8.55, 'GEECEE': 44.15, 'GEEKAYWIRE': 9.95, 'GENCON': None, 'GENESYS': 24.25, 'GENSOL': None, 'GENUSPAPER': 3.15, 'GENUSPOWER': 13.95, 'GEOJITFSL': 18.2, 'GEPIL': 475.0, 'GESHIP': 205.8, 'GFLLIMITED': 82.1, 'GFSTEELS': 1.45, 'GGBL_SME': None, 'GHCL': 89.15, 'GHCLTEXTIL': None, 'GICHSGFIN': 59.4, 'GICL_SME': None, 'GICRE': 105.2, 'GILLANDERS': 20.0, 'GILLETTE': 5470.1, 'GILT5YBEES': None, 'GINNIFILA': 6.1, 'GIPCL': 49.9, 'GIRIRAJ_SME': None, 'GKWLIMITED': 461.0, 'GLAND': None, 'GLAXO': 1257.4, 'GLENMARK': 205.85, 'GLFL': 1.4, 'GLOBAL': 10.85, 'GLOBALE': None, 'GLOBALPET_SME': None, 'GLOBALVECT': 35.85, 'GLOBE': None, 'GLOBUSSPR': 84.45, 'GLOSTERLTD': None, 'GMBREW': 247.3, 'GMDCLTD': 31.55, 'GMMPFAUDLR': 837.6, 'GMRAIRPORT': 16.35, 'GMRP&UI': None, 'GNA': 70.55, 'GNFC': 114.7, 'GOACARBON': 124.2, 'GOCLCORP': 127.0, 'GOCOLORS': None, 'GODAVARIB': None, 'GODFRYPHLP': 940.5, 'GODHA': 1.0, 'GODIGIT': None, 'GODREJAGRO': 367.75, 'GODREJCP': 520.85, 'GODREJIND': 283.15, 'GODREJPROP': 603.25, 'GOENKA': 0.25, 'GOKEX': 32.55, 'GOKUL': 8.4, 'GOKULAGRO': 8.45, 'GOLD1': 387.0, 'GOLD360': None, 'GOLDBEES': 38.21, 'GOLDCASE': None, 'GOLDENTOBC': 19.7, 'GOLDETF': None, 'GOLDETFADD': None, 'GOLDIAM': 17.45, 'GOLDIETF': 39.39, 'GOLDKART_SME': None, 'GOLDSHARE': 3825.65, 'GOLDSTAR_SME': None, 'GOLDTECH': 7.8, 'GOODLUCK': 25.25, 'GOPAL': None, 'GOYALALUM': None, 'GOYALSALT_SME': None, 'GPECO_SME': None, 'GPIL': 5.25, 'GPPL': 60.25, 'GPTHEALTH': None, 'GPTINFRA': 3.6, 'GRANULES': 143.65, 'GRAPHISAD_SME': None, 'GRAPHITE': 127.25, 'GRASIM': 476.1, 'GRAVITA': 33.45, 'GRCL_SME': None, 'GREAVESCOT': 69.55, 'GREENCHEF_SME': None, 'GREENLAM': 99.4, 'GREENPANEL': 28.6, 'GREENPLY': 81.05, 'GREENPOWER': 1.45, 'GRETEX_SME': None, 'GRINDWELL': 456.2, 'GRINFRA': None, 'GRMOVER': None, 'GROBTEA': 259.25, 'GROWWDEFNC': None, 'GROWWEV': None, 'GROWWGOLD': None, 'GROWWLIQID': None, 'GROWWN200': None, 'GROWWRAIL': None, 'GRPLTD': 154.0, 'GRSE': 136.6, 'GRWRHITECH': None, 'GSEC10ABSL': None, 'GSEC10IETF': None, 'GSEC10YEAR': None, 'GSEC5IETF': None, 'GSFC': 36.55, 'GSLSU': None, 'GSMFOILS_SME': None, 'GSPL': 172.45, 'GSS': 19.05, 'GSTL_SME': None, 'GTECJAINX': None, 'GTL': 1.15, 'GTLINFRA': 0.25, 'GTPL': 41.75, 'GUFICBIO': 47.85, 'GUJALKALI': 223.0, 'GUJAPOLLO': 120.0, 'GUJGASLTD': 230.85, 'GUJRAFFIA': 7.6, 'GUJTHEM': None, 'GULFOILLUB': 514.75, 'GULFPETRO': 30.5, 'GULPOLY': 17.75, 'GVKPIL': None, 'GVPTECH': None, 'GVT&D': 71.9, 'HAL': 260.15, 'HAPPSTMNDS': None, 'HAPPYFORGE': None, 'HARDWYN': None, 'HARIOMPIPE': None, 'HARRMALAYA': 53.1, 'HARSHA': None, 'HATHWAY': 13.45, 'HATSUN': 387.55, 'HAVELLS': 480.45, 'HAVISHA': 0.45, 'HBLENGINE': 11.0, 'HBSL': None, 'HCC': 3.95, 'HCG': 74.1, 'HCL-INSYS': 3.65, 'HCLTECH': 436.4, 'HDFCAMC': 2112.8, 'HDFCBANK': 861.9, 'HDFCBSE500': None, 'HDFCGOLD': 3953.6, 'HDFCGROWTH': None, 'HDFCLIFE': 441.35, 'HDFCLIQUID': None, 'HDFCLOWVOL': None, 'HDFCMID150': None, 'HDFCMOMENT': None, 'HDFCNEXT50': None, 'HDFCNIF100': None, 'HDFCNIFBAN': None, 'HDFCNIFIT': None, 'HDFCNIFTY': 917.87, 'HDFCPSUBK': None, 'HDFCPVTBAN': None, 'HDFCQUAL': None, 'HDFCSENSEX': 3222.95, 'HDFCSILVER': None, 'HDFCSML250': None, 'HDFCVALUE': None, 'HDIL': 1.4, 'HEADSUP': 5.95, 'HEALTHADD': None, 'HEALTHIETF': None, 'HEALTHY': None, 'HECPROJECT': None, 'HEG': 96.8, 'HEIDELBERG': 141.85, 'HEMIPROP': None, 'HERANBA': None, 'HERCULES': 51.0, 'HERITGFOOD': 212.5, 'HEROMOTOCO': 1596.45, 'HESTERBIO': 920.45, 'HEUBACHIND': 227.3, 'HEXATRADEX': 6.4, 'HEXT': None, 'HFCL': 9.05, 'HGINFRA': 173.55, 'HGS': 252.4, 'HIGREEN_SME': None, 'HIKAL': 69.65, 'HIL': 630.2, 'HILTON': 7.0, 'HIMATSEIDE': 59.55, 'HINDALCO': 95.7, 'HINDCOMPOS': 109.8, 'HINDCON': None, 'HINDCOPPER': 21.3, 'HINDMOTORS': 3.05, 'HINDNATGLS': 27.65, 'HINDOILEXP': 34.75, 'HINDPETRO': 126.75, 'HINDUNILVR': 2298.5, 'HINDWAREAP': 67.95, 'HINDZINC': 155.4, 'HIRECT': 115.55, 'HISARMETAL': 41.3, 'HITECH': 7.2, 'HITECHCORP': 48.55, 'HITECHGEAR': 78.8, 'HLEGLAS': None, 'HLVLTD': 3.15, 'HMAAGRO': None, 'HMT': 8.35, 'HMVL': 38.05, 'HNDFDS': 112.3, 'HNGSNGBEES': None, 'HOACFOODS_SME': None, 'HOLMARC_SME': None, 'HOMEFIRST': None, 'HOMESFY_SME': None, 'HONASA': None, 'HONAUT': 25890.6, 'HONDAPOWER': 840.4, 'HOVS': 22.9, 'HPAL': None, 'HPIL': 40.9, 'HPL': 21.55, 'HPTL_SME': None, 'HRHNEXT_SME': None, 'HSCL': 29.45, 'HTMEDIA': 10.0, 'HUBTOWN': 7.8, 'HUDCO': 20.0, 'HUHTAMAKI': 195.6, 'HVAX_SME': None, 'HYBRIDFIN': None, 'HYUNDAI': None, 'IBLFL_SME': None, 'ICDSLTD': None, 'ICEMAKE': None, 'ICICIB22': 22.87, 'ICICIBANK': 323.75, 'ICICIGI': 1081.65, 'ICICIPRULI': 355.7, 'ICIL': 23.8, 'ICRA': 2144.7, 'IDBI': 19.3, 'IDEA': 3.1, 'IDEAFORGE': None, 'IDEALTECHO_SME': None, 'IDENTICAL_SME': None, 'IDFC': 14.85, 'IDFCFIRSTB': 21.1, 'IDFNIFTYET': 101.0, 'IEL': None, 'IEML_SME': None, 'IEX': 42.65, 'IFBAGRO': 238.2, 'IFBIND': 

      STOCKNAME  PRICE0320
2957       ZOTA     130.25
2959      ZUARI      61.75
2960   ZUARIIND      27.40
2961  ZYDUSLIFE     267.25
2962  ZYDUSWELL    1299.35

In [ ]:
merged_final = pd.merge(merged_df, df, how='inner', left_on='Stock Code', right_on='STOCKNAME')
merged_final.head()

,Sr.No.,Accord Code,Company Name,FR_ROA (%)4,FR_ROE (%)4,FR_ROCE (%)4,FR_Asset Turnover(x)4,FR_Year End4,FR_Adjusted PE (x)4,FR_Price / Book Value(x)4,...,RoA Annual %,Sector Return on Assets,Industry Return on Assets,Piotroski Score,sector_name,Industry Name.1,Latest financial result,Result Announced Date,STOCKNAME,PRICE0320
0,1,207635.0,20 Microns Ltd.,5.435195,13.610332,18.907800,1.193281,202003.0,3.760279,0.482881,...,9.50,10.88,17.60,7.0,Metals & Mining,Coal & Mining,2024-12-31,2025-01-22,20MICRONS,25.55
1,3,228974.0,360 One Wam Ltd.,1.765841,6.857861,7.561351,0.129037,202003.0,42.763386,2.900420,...,5.31,2.86,8.70,3.0,Banking and Finance,Capital Markets,2024-12-31,2025-04-23,360ONE,251.45
2,6,123395.0,3M India Ltd.,14.523256,20.238612,27.285532,1.346325,202003.0,66.138604,12.169831,...,15.77,11.85,12.40,8.0,General Industrials,Industrial Machinery,2024-12-31,2025-02-07,3MINDIA,18827.95
3,7,116092.0,3P Land Holdings Ltd.,13.054406,13.268980,14.073961,0.054392,202003.0,1.467005,0.184927,...,1.73,4.59,4.99,5.0,Realty,Realty,2024-12-31,2025-01-18,3PLAND,3.55
4,9,228972.0,5Paisa Capital Ltd.,-1.833797,-8.821656,2.291769,0.251334,202003.0,0.000000,2.093420,...,2.65,2.86,8.70,4.0,Banking and Finance,Capital Markets,2024-12-31,2025-05-01,5PAISA,113.15

In [22]:
merged_final.to_csv('merged_final.csv', index=False)

In [53]:
df['FR_ROA (%)4'] = pd.to_numeric(df['FR_ROA (%)4'], errors='coerce')
df['Current Price'] = pd.to_numeric(df['Current Price'], errors='coerce')
df['PRICE0320'] = pd.to_numeric(df['PRICE0320'], errors='coerce')

sorted_df = df.sort_values(by='FR_ROA (%)4', ascending=False)

top_100 = sorted_df.head(200).copy()

top_100['Percent Change'] = ((top_100['Current Price'] - top_100['PRICE0320']) / top_100['PRICE0320']) * 100

top_100[['Company Name', 'Current Price', 'PRICE0320', 'Percent Change']].head(10)

,Company Name,Current Price,PRICE0320,Percent Change
848,Patanjali Foods Ltd.,1959.00,172.05,1038.622493
796,NIIT Ltd.,143.81,82.20,74.951338
1232,Vardhman Polytex Ltd.,12.90,0.35,3585.714286
483,Hindustan Unilever Ltd.,2422.00,2298.50,5.373069
301,Dolat Algotech Ltd.,94.25,35.25,167.375887
452,HDFC Asset Management Company Ltd.,4552.00,2112.80,115.448694
263,Cupid Ltd.,73.10,7.05,936.879433
232,Cigniti Technologies Ltd.,1359.50,189.05,619.121925
1115,Suven Pharmaceuticals Ltd.,1205.00,100.50,1099.004975
1286,Zen Technologies Ltd.,1439.90,22.75,6229.230769

In [54]:
percent_change_sum = top_100['Percent Change'].mean()
percent_change_sum

452.8047086490115

In [55]:
df['FR_ROA (%)4'] = pd.to_numeric(df['FR_ROA (%)4'], errors='coerce')
df['Current Price'] = pd.to_numeric(df['Current Price'], errors='coerce')
df['PRICE0320'] = pd.to_numeric(df['PRICE0320'], errors='coerce')

sorted_df = df.sort_values(by='FR_ROA (%)4', ascending=True)

top_100 = sorted_df.head(200).copy()

top_100['Percent Change'] = ((top_100['PRICE0320'] - top_100['Current Price']) / top_100['PRICE0320']) * 100

top_100[['Company Name', 'Current Price', 'PRICE0320', 'Percent Change']].head(100)

,Company Name,Current Price,PRICE0320,Percent Change
1070,Spacenet Enterprises India Ltd.,9.00,0.90,-900.000000
554,Integra Essentia Ltd.,2.46,0.10,-2360.000000
1140,Tata Teleservices (Maharashtra) Ltd.,61.18,1.80,-3298.888889
992,Sanwaria Consumer Ltd.,0.41,1.05,60.952381
605,Jyoti Structures Ltd.,21.50,1.30,-1553.846154
...,...,...,...,...
855,Pearl Polymers Ltd.,29.35,12.95,-126.640927
413,Golden Tobacco Ltd.,35.72,19.70,-81.319797
282,Delta Manufacturing Ltd.,63.91,27.00,-136.703704
450,HCL Infosystems Ltd.,14.10,3.65,-286.301370
91,Arshiya Ltd.,3.15,6.80,53.676471

In [56]:
percent_change_sum = top_100['Percent Change'].mean()
percent_change_sum

-1096.063774330853

In [59]:
import pandas as pd
import os

# Folder path where your CSV files are stored
folder_path = "C:/Users/meets/nse-benny/eod2/src/eod2_data/daily"

# Initialize an empty list to store DataFrames
close_prices = []

# Loop through all files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.csv'):
        file_path = os.path.join(folder_path, filename)
        df = pd.read_csv(file_path)
        # Use the filename (without .csv) as the stock name
        stock_name = os.path.splitext(filename)[0]
        # Extract 'Close' column and rename it with the stock name
        if 'Close' in df.columns:
            close_prices.append(df[['Close']].rename(columns={'Close': stock_name}))

# Combine all 'Close' columns into a single DataFrame
combined_df = pd.concat(close_prices, axis=1)

# Show the result
print(combined_df.head())

   20microns  21stcenmgm  360one  3iinfoltd  3mindia  3pland  5paisa  63moons  \
0      16.80       33.40  317.60      31.00   404.05    30.7  380.00   386.90
1      15.05       34.05  333.50      32.55   403.00    29.6  361.00   405.70
2      13.25       34.70  350.20      34.15   408.65    31.1  342.95   437.90
3      11.60       35.35  367.70      35.85   402.00    32.7  325.85   437.10
4      12.30       36.05  351.25      37.60   406.45    31.5  309.60   434.85

   a2zinfra  aaatech  ...  zimlab  zodiac  zodiacloth  zomato    zota  \
0    328.55    43.60  ...  112.15    51.1       38.45  126.00  125.60
1    332.10    43.00  ...  108.70    46.1       37.75  140.65  127.00
2    325.45    43.30  ...  107.00    51.8       38.25  132.90  127.25
3    317.65    43.70  ...  105.25    53.0       35.55  131.20  127.20
4    317.00    43.45  ...  105.85    51.7       37.75  141.55  128.80

   ztech_sme   zuari  zuariind  zyduslife  zyduswell
0     105.00  374.30     425.0       8.70     200.55
1     110.25  355.60     427.5       8.00     196.60
2     115.75  337.85     422.5       7.35     210.65
3     121.50  321.00     420.0       6.85     207.05
4     127.55  304.95     380.0       7.40     203.00

[5 rows x 2963 columns]

In [60]:
import pandas as pd
import os

# Folder path where your CSV files are stored
folder_path = "C:/Users/meets/nse-benny/eod2/src/eod2_data/daily"

# Initialize an empty list to store individual DataFrames
all_data = []

# Loop through all CSV files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.csv'):
        file_path = os.path.join(folder_path, filename)
        df = pd.read_csv(file_path)
        
        # Check if both 'Date' and 'Close' columns exist
        if 'Date' in df.columns and 'Close' in df.columns:
            stock_name = os.path.splitext(filename)[0]
            # Extract and rename the columns
            temp_df = df[['Date', 'Close']].copy()
            temp_df.rename(columns={'Close': stock_name}, inplace=True)
            all_data.append(temp_df)

# Merge all DataFrames on the 'Date' column
from functools import reduce
combined_df = reduce(lambda left, right: pd.merge(left, right, on='Date', how='outer'), all_data)

# Convert 'Date' to datetime format for sorting (optional)
combined_df['Date'] = pd.to_datetime(combined_df['Date'])
combined_df.sort_values('Date', inplace=True)

# Reset index
combined_df.reset_index(drop=True, inplace=True)

# Show the result
print(combined_df.head())

        Date  20microns  21stcenmgm  360one  3iinfoltd  3mindia  3pland  \
0 1995-01-02        NaN         NaN     NaN        NaN      NaN     NaN
1 1995-01-03        NaN         NaN     NaN        NaN      NaN     NaN
2 1995-01-04        NaN         NaN     NaN        NaN      NaN     NaN
3 1995-01-05        NaN         NaN     NaN        NaN      NaN     NaN
4 1995-01-06        NaN         NaN     NaN        NaN      NaN     NaN

   5paisa  63moons  a2zinfra  ...  zimlab  zodiac  zodiacloth  zomato  zota  \
0     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
1     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
2     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
3     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
4     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN

   ztech_sme  zuari  zuariind  zyduslife  zyduswell
0        NaN    NaN     425.0        NaN        NaN
1        NaN    NaN     427.5        NaN        NaN
2        NaN    NaN     422.5        NaN        NaN
3        NaN    NaN       NaN        NaN        NaN
4        NaN    NaN     420.0        NaN        NaN

[5 rows x 2964 columns]

In [61]:
combined_df.to_csv("mega_dateclose.csv", index=False)

In [1]:
import pandas as pd
import os

# Folder path where your CSV files are stored
folder_path = "C:/Users/meets/nse-benny/eod2/src/eod2_data/daily"

# Initialize an empty list to store individual DataFrames
all_data = []

# Loop through all CSV files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.csv'):
        file_path = os.path.join(folder_path, filename)
        df = pd.read_csv(file_path)
        
        # Check if both 'Date' and 'Close' columns exist
        if 'Date' in df.columns and 'Volume' in df.columns:
            stock_name = os.path.splitext(filename)[0]
            # Extract and rename the columns
            temp_df = df[['Date', 'Volume']].copy()
            temp_df.rename(columns={'Volume': stock_name}, inplace=True)
            all_data.append(temp_df)

# Merge all DataFrames on the 'Date' column
from functools import reduce
combined_df = reduce(lambda left, right: pd.merge(left, right, on='Date', how='outer'), all_data)

# Convert 'Date' to datetime format for sorting (optional)
combined_df['Date'] = pd.to_datetime(combined_df['Date'])
combined_df.sort_values('Date', inplace=True)

# Reset index
combined_df.reset_index(drop=True, inplace=True)

# Show the result
print(combined_df.head())

        Date  20microns  21stcenmgm  360one  3iinfoltd  3mindia  3pland  \
0 1995-01-02        NaN         NaN     NaN        NaN      NaN     NaN
1 1995-01-03        NaN         NaN     NaN        NaN      NaN     NaN
2 1995-01-04        NaN         NaN     NaN        NaN      NaN     NaN
3 1995-01-05        NaN         NaN     NaN        NaN      NaN     NaN
4 1995-01-06        NaN         NaN     NaN        NaN      NaN     NaN

   5paisa  63moons  a2zinfra  ...  zimlab  zodiac  zodiacloth  zomato  zota  \
0     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
1     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
2     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
3     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
4     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN

   ztech_sme  zuari  zuariind  zyduslife  zyduswell
0        NaN    NaN     100.0        NaN        NaN
1        NaN    NaN     100.0        NaN        NaN
2        NaN    NaN     200.0        NaN        NaN
3        NaN    NaN       NaN        NaN        NaN
4        NaN    NaN     250.0        NaN        NaN

[5 rows x 2964 columns]

In [2]:
combined_df.columns = [col.upper() if col.lower() != 'Date' else col for col in combined_df.columns]
print(combined_df.head())

        DATE  20MICRONS  21STCENMGM  360ONE  3IINFOLTD  3MINDIA  3PLAND  \
0 1995-01-02        NaN         NaN     NaN        NaN      NaN     NaN
1 1995-01-03        NaN         NaN     NaN        NaN      NaN     NaN
2 1995-01-04        NaN         NaN     NaN        NaN      NaN     NaN
3 1995-01-05        NaN         NaN     NaN        NaN      NaN     NaN
4 1995-01-06        NaN         NaN     NaN        NaN      NaN     NaN

   5PAISA  63MOONS  A2ZINFRA  ...  ZIMLAB  ZODIAC  ZODIACLOTH  ZOMATO  ZOTA  \
0     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
1     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
2     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
3     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN
4     NaN      NaN       NaN  ...     NaN     NaN         NaN     NaN   NaN

   ZTECH_SME  ZUARI  ZUARIIND  ZYDUSLIFE  ZYDUSWELL
0        NaN    NaN     100.0        NaN        NaN
1        NaN    NaN     100.0        NaN        NaN
2        NaN    NaN     200.0        NaN        NaN
3        NaN    NaN       NaN        NaN        NaN
4        NaN    NaN     250.0        NaN        NaN

[5 rows x 2964 columns]

In [3]:
combined_df.to_csv("mega_datevol_final.csv", index=False)

In [7]:
# Re-run the calculation and output due to the previous error
df = pd.read_csv("mega_datevol_final.csv")
df['DATE'] = pd.to_datetime(df['DATE'])
# Recalculate the 30-day moving average
ma_df = df.rolling(window=30).mean()
ma_df.set_index('DATE', inplace=True)
ma_df.columns = [f"MA_{col}" for col in ma_df.columns]

# Concatenate original data with moving averages
result_df = pd.concat([df, ma_df], axis=1)

# Display the first 35 rows to show initial moving averages
result_df.head(35)

DataError: Cannot aggregate non-numeric type: datetime64[ns]