In [22]:
import pandas as pd

In [23]:
df1 = pd.read_excel("New_S2.xlsx")
df1.tail()

,Sr.No.,Accord Code,Company Name,BS_Year end date,BS_Share Capital,BS_Year end date1,BS_Share Capital1,BS_Year End,BS_Total Debt (Long Term Plus Short Term),BS_Total Debt (Long Term Plus Short Term)1,...,BS_Gross Block1,BS_Capital Work in Progress1,CD_BSE Code,CD_NSE Symbol,FH_Market Capitalization,CONS_BS_1,CONS_BS_2,CONS_BS_3,CONS_BS_4,CONS_FH_1
73,74,310038,Vilin Bio Med Ltd.,2024-03-31,13.950000,2023-03-31,9.950000,202403,6.829900,4.931200,...,9.384600,NaN,NaN,VILINBIO,26.505000,S,S,S,S,S
74,75,291579,Vivanta Industries Ltd.,2024-03-31,12.500000,2023-03-31,10.000000,202403,15.841400,4.369200,...,14.115600,NaN,541735.0,NaN,44.875000,C,C,C,C,C
75,76,124212,Wanbury Ltd.,2024-03-31,32.745500,2023-03-31,32.705500,202403,109.952000,64.137900,...,239.286300,1.6058,524212.0,WANBURY,477.593118,C,C,C,C,C
76,77,132373,WEP Solutions Ltd.,2024-03-31,36.600900,2023-03-31,36.353700,202403,11.767100,3.371800,...,79.788900,1.7565,532373.0,NaN,138.532136,S,S,S,C,S
77,78,106640,ZR2 Bioenergy Ltd.,2024-03-31,0.356885,2023-03-31,0.161885,202403,22.009099,12.010356,...,0.225752,NaN,506640.0,NaN,28.347376,S,S,S,S,S

In [24]:
# df1['Gross_Plus_CWIP_chg'] = ((df1['BS_Capital Work in Progress']/df1['BS_Capital Work in Progress1'])-1) * 100


#LOWER THE BETTER SO * -1
mean_value = df1['CAPEX Growth'].mean()
std_dev = df1['CAPEX Growth'].std()
df1['ZSCORE_CAPEX'] = ((df1['CAPEX Growth']-mean_value) / std_dev) * (-1)


mean_value = df1['Debt Growth'].mean()
std_dev = df1['Debt Growth'].std()
df1['ZSCORE_DEBTGROWTH'] = (df1['Debt Growth']-mean_value) / std_dev


mean_value = df1['BS_Share Capital'].mean()
std_dev = df1['BS_Share Capital'].std()
df1['ZSCORE_SHARECAPITAL'] = (df1['BS_Share Capital']-mean_value) / std_dev


mean_value = df1['FH_Market Capitalization'].mean()
std_dev = df1['FH_Market Capitalization'].std()
df1['ZSCORE_MCAP'] = (df1['FH_Market Capitalization']-mean_value) / std_dev


df1.head()

,Sr.No.,Accord Code,Company Name,BS_Year end date,BS_Share Capital,BS_Year end date1,BS_Share Capital1,BS_Year End,BS_Total Debt (Long Term Plus Short Term),BS_Total Debt (Long Term Plus Short Term)1,...,FH_Market Capitalization,CONS_BS_1,CONS_BS_2,CONS_BS_3,CONS_BS_4,CONS_FH_1,ZSCORE_CAPEX,ZSCORE_DEBTGROWTH,ZSCORE_SHARECAPITAL,ZSCORE_MCAP
0,1,315106,Aesthetik Engineers Ltd.,2024-03-31,12.656175,2023-03-31,0.843745,202403,8.499209,5.924653,...,0.000000,C,C,S,S,C,-0.464827,-0.146500,-0.395570,-0.353762
1,2,314657,Afcom Holdings Ltd.,2024-03-31,18.021300,2023-03-31,17.603800,202403,18.475300,0.476000,...,0.000000,S,S,S,S,S,-0.064639,0.281610,-0.319268,-0.353762
2,3,313489,Akiko Global Services Ltd.,2024-03-31,7.768000,2023-03-31,0.040000,202403,1.279500,0.958900,...,0.000000,S,S,S,S,S,-0.498663,-0.147648,-0.465089,-0.353762
3,4,131082,Alankit Ltd.,2024-03-31,27.115800,2023-03-31,22.455800,202403,43.635900,13.463900,...,481.576608,C,C,C,C,C,-0.115543,-0.125811,-0.189928,-0.292298
4,5,313837,Ambey Laboratories Ltd.,2024-03-31,18.688800,2023-03-31,17.749400,202403,29.644300,14.121500,...,0.000000,S,S,S,S,S,-0.659100,-0.138887,-0.309775,-0.353762

In [25]:
df2 = pd.read_excel("TRENDLYNE_230425.xlsx")
df2.head()

,Stock Name,NSE Code,BSE Code,Stock Code,ISIN,Industry Name,Current Price,Current Price.1,Market Capitalization,PE TTM Price to Earnings,...,Sector Return on Equity ROE,Industry Return on Equity ROE,RoA Annual %,Sector Return on Assets,Industry Return on Assets,Piotroski Score,sector_name,Industry Name.1,Latest financial result,Result Announced Date
0,20 Microns Ltd.,20MICRONS,533022.0,20MICRONS,INE144J01027,Coal & Mining,227.25,227.25,801.89,13.19,...,23.96,38.63,9.50,10.88,17.60,7.0,Metals & Mining,Coal & Mining,2024-12-31,2025-01-22
1,360 ONE Gold ETF,GOLD360,544375.0,GOLD360,INF579M01BB5,Others,95.45,95.45,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Others,Others,NaT,NaT
2,360 ONE Silver ETF,SILVER360,544389.0,SILVER360,INF579M01BC3,Others,99.20,99.20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Others,Others,NaT,NaT
3,360 One Wam Ltd.,360ONE,542772.0,360ONE,INE466L01038,Capital Markets,1057.00,1057.00,41613.87,41.27,...,17.25,23.88,5.31,2.86,8.70,3.0,Banking and Finance,Capital Markets,2024-12-31,2025-04-23
4,3B BlackBio Dx Ltd.,NaN,532067.0,3BBLACKBIO,INE994E01018,Agrochemicals,1784.05,1784.05,1531.20,31.87,...,14.53,17.06,12.93,9.90,12.59,7.0,Chemicals & Petrochemicals,Agrochemicals,2024-12-31,2025-02-13

In [26]:
df1['CD_BSE Code'] = pd.to_numeric(df1['CD_BSE Code'], errors='coerce')
df2['BSE Code'] = pd.to_numeric(df2['BSE Code'], errors='coerce')

df1['CD_NSE Symbol'] = df1['CD_NSE Symbol'].astype(str).str.upper()
df2['NSE Code'] = df2['NSE Code'].astype(str).str.upper()

# Deduplicate df2 to avoid one-to-many joins
df2_bse_dedup = df2.drop_duplicates(subset='BSE Code')
df2_nse_dedup = df2.drop_duplicates(subset='NSE Code')

# Step 1: Join on BSE Code
merged_bse = df1.merge(df2_bse_dedup, how='left', left_on='CD_BSE Code', right_on='BSE Code', indicator=True)

# Step 2: Filter unmatched and join them on NSE Code
unmatched = merged_bse[merged_bse['_merge'] == 'left_only'].copy()
matched = merged_bse[merged_bse['_merge'] == 'both'].copy()

# Remove merged df2 columns from unmatched before re-joining
unmatched_clean = unmatched[df1.columns]

# Join unmatched on NSE Code
merged_nse = unmatched_clean.merge(df2_nse_dedup, how='left', left_on='CD_NSE Symbol', right_on='NSE Code')

# Combine both
final_merged = pd.concat([matched.drop(columns=['_merge']), merged_nse], ignore_index=True)

# Optional: Save to Excel
# final_merged.to_csv("visual_tp.csv",index=False)
final_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 67 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Sr.No.                                           78 non-null     int64
 1   Accord Code                                      78 non-null     int64
 2   Company Name                                     78 non-null     object
 3   BS_Year end date                                 78 non-null     datetime64[ns]
 4   BS_Share Capital                                 78 non-null     float64
 5   BS_Year end date1                                78 non-null     datetime64[ns]
 6   BS_Share Capital1                                78 non-null     float64
 7   BS_Year End                                      78 non-null     int64
 8   BS_Total Debt (Long Term Plus Short Term)        78 non-null     float64
 9   BS_Total Debt (Long Term Plus Short Term)1       78 non-null     float64
 10  Debt Growth                                      78 non-null     float64
 11  CAPEX Growth                                     78 non-null     float64
 12  BS_Year end date2                                78 non-null     datetime64[ns]
 13  BS_Gross Block                                   78 non-null     float64
 14  BS_Capital Work in Progress                      25 non-null     float64
 15  BS_Year end date3                                78 non-null     datetime64[ns]
 16  BS_Gross Block1                                  78 non-null     float64
 17  BS_Capital Work in Progress1                     30 non-null     float64
 18  CD_BSE Code                                      59 non-null     float64
 19  CD_NSE Symbol                                    78 non-null     object
 20  FH_Market Capitalization                         78 non-null     float64
 21  CONS_BS_1                                        78 non-null     object
 22  CONS_BS_2                                        78 non-null     object
 23  CONS_BS_3                                        78 non-null     object
 24  CONS_BS_4                                        78 non-null     object
 25  CONS_FH_1                                        78 non-null     object
 26  ZSCORE_CAPEX                                     78 non-null     float64
 27  ZSCORE_DEBTGROWTH                                78 non-null     float64
 28  ZSCORE_SHARECAPITAL                              78 non-null     float64
 29  ZSCORE_MCAP                                      78 non-null     float64
 30  Stock Name                                       78 non-null     object
 31  NSE Code                                         78 non-null     object
 32  BSE Code                                         59 non-null     float64
 33  Stock Code                                       78 non-null     object
 34  ISIN                                             78 non-null     object
 35  Industry Name                                    78 non-null     object
 36  Current Price                                    78 non-null     float64
 37  Current Price.1                                  78 non-null     float64
 38  Market Capitalization                            78 non-null     float64
 39  PE TTM Price to Earnings                         78 non-null     float64
 40  Forecaster Estimates 1Y forward PE               78 non-null     object
 41  PE 3Yr Average                                   45 non-null     float64
 42  PE 5Yr Average                                   40 non-null     float64
 43  %Days traded below current PE Price to Earnings  45 non-null     float64
 44  Sector PE TTM                                    78 non-null     float64
 45  Industry PE TTM                                  78 non-null     float64
 46  PEG TTM PE to Growth                             47 non-null     float64
 47  Forecaster Estimates 1Y forward PEG              78 non-null     object
 48  Sector PEG TTM                                   78 non-null     float64
 49  Industry PEG TTM                                 78 non-null     float64
 50  Price to Book Value                              78 non-null     float64
 51  %Days traded below current Price to Book Value   55 non-null     float64
 52  Sector Price to Book TTM                         78 non-null     float64
 53  Industry Price to Book TTM                       78 non-null     float64
 54  Basic EPS TTM                                    78 non-null     float64
 55  EPS TTM Growth %                                 47 non-null     float64
 56  ROE Annual %                                     78 non-null     float64
 57  Sector Return on Equity ROE                      78 non-null     float64
 58  Industry Return on Equity ROE                    78 non-null     float64
 59  RoA Annual %                                     78 non-null     float64
 60  Sector Return on Assets                          78 non-null     float64
 61  Industry Return on Assets                        78 non-null     float64
 62  Piotroski Score                                  78 non-null     float64
 63  sector_name                                      78 non-null     object
 64  Industry Name.1                                  78 non-null     object
 65  Latest financial result                          78 non-null     datetime64[ns]
 66  Result Announced Date                            78 non-null     datetime64[ns]
dtypes: datetime64[ns](6), float64(42), int64(3), object(16)
memory usage: 41.0+ KB

In [27]:
# Set the DATE column as the index for rolling operation
column_list = final_merged['Stock Code'].tolist()

vol_df = pd.read_csv("C:/Users/meets/AVENTUS_FACTOR-MODEL/SIMPLE STRATEGY/mega_datevol_final.csv")
vol_df['DATE'] = pd.to_datetime(vol_df['DATE'])

vol_df.set_index('DATE', inplace=True)

# Filter column_list to only include columns present in vol_df
valid_columns = [col for col in column_list if col in vol_df.columns]

# Apply rolling mean with a window of 20 days and min_periods=1
rolling_means = vol_df[valid_columns].rolling(window=20, min_periods=1).mean()

# Extract the rolling average values as of 2009-04-01
rolling_avg_at_date = rolling_means.loc[pd.Timestamp('2025-03-03')]

# Store the result in a DataFrame
result_df_updated = pd.DataFrame({
    'STOCK NAME': rolling_avg_at_date.index,
    'MA': rolling_avg_at_date.values
})

# result_df_updated.info()

merged_df_1 = pd.merge(final_merged, result_df_updated, how='inner', left_on='Stock Code', right_on='STOCK NAME')
merged_df_1.info()

merged_df = merged_df_1[(merged_df_1["Market Capitalization"] >= 1000) & (merged_df_1["MA"] >= 10000)]

# Show the number of rows removed and preview the cleaned data
rows_removed = len(merged_df_1) - len(merged_df)
merged_df.head(), rows_removed

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 69 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Sr.No.                                           30 non-null     int64
 1   Accord Code                                      30 non-null     int64
 2   Company Name                                     30 non-null     object
 3   BS_Year end date                                 30 non-null     datetime64[ns]
 4   BS_Share Capital                                 30 non-null     float64
 5   BS_Year end date1                                30 non-null     datetime64[ns]
 6   BS_Share Capital1                                30 non-null     float64
 7   BS_Year End                                      30 non-null     int64
 8   BS_Total Debt (Long Term Plus Short Term)        30 non-null     float64
 9   BS_Total Debt (Long Term Plus Short Term)1       30 non-null     float64
 10  Debt Growth                                      30 non-null     float64
 11  CAPEX Growth                                     30 non-null     float64
 12  BS_Year end date2                                30 non-null     datetime64[ns]
 13  BS_Gross Block                                   30 non-null     float64
 14  BS_Capital Work in Progress                      14 non-null     float64
 15  BS_Year end date3                                30 non-null     datetime64[ns]
 16  BS_Gross Block1                                  30 non-null     float64
 17  BS_Capital Work in Progress1                     20 non-null     float64
 18  CD_BSE Code                                      30 non-null     float64
 19  CD_NSE Symbol                                    30 non-null     object
 20  FH_Market Capitalization                         30 non-null     float64
 21  CONS_BS_1                                        30 non-null     object
 22  CONS_BS_2                                        30 non-null     object
 23  CONS_BS_3                                        30 non-null     object
 24  CONS_BS_4                                        30 non-null     object
 25  CONS_FH_1                                        30 non-null     object
 26  ZSCORE_CAPEX                                     30 non-null     float64
 27  ZSCORE_DEBTGROWTH                                30 non-null     float64
 28  ZSCORE_SHARECAPITAL                              30 non-null     float64
 29  ZSCORE_MCAP                                      30 non-null     float64
 30  Stock Name                                       30 non-null     object
 31  NSE Code                                         30 non-null     object
 32  BSE Code                                         30 non-null     float64
 33  Stock Code                                       30 non-null     object
 34  ISIN                                             30 non-null     object
 35  Industry Name                                    30 non-null     object
 36  Current Price                                    30 non-null     float64
 37  Current Price.1                                  30 non-null     float64
 38  Market Capitalization                            30 non-null     float64
 39  PE TTM Price to Earnings                         30 non-null     float64
 40  Forecaster Estimates 1Y forward PE               30 non-null     object
 41  PE 3Yr Average                                   23 non-null     float64
 42  PE 5Yr Average                                   22 non-null     float64
 43  %Days traded below current PE Price to Earnings  29 non-null     float64
 44  Sector PE TTM                                    30 non-null     float64
 45  Industry PE TTM                                  30 non-null     float64
 46  PEG TTM PE to Growth                             29 non-null     float64
 47  Forecaster Estimates 1Y forward PEG              30 non-null     object
 48  Sector PEG TTM                                   30 non-null     float64
 49  Industry PEG TTM                                 30 non-null     float64
 50  Price to Book Value                              30 non-null     float64
 51  %Days traded below current Price to Book Value   29 non-null     float64
 52  Sector Price to Book TTM                         30 non-null     float64
 53  Industry Price to Book TTM                       30 non-null     float64
 54  Basic EPS TTM                                    30 non-null     float64
 55  EPS TTM Growth %                                 29 non-null     float64
 56  ROE Annual %                                     30 non-null     float64
 57  Sector Return on Equity ROE                      30 non-null     float64
 58  Industry Return on Equity ROE                    30 non-null     float64
 59  RoA Annual %                                     30 non-null     float64
 60  Sector Return on Assets                          30 non-null     float64
 61  Industry Return on Assets                        30 non-null     float64
 62  Piotroski Score                                  30 non-null     float64
 63  sector_name                                      30 non-null     object
 64  Industry Name.1                                  30 non-null     object
 65  Latest financial result                          30 non-null     datetime64[ns]
 66  Result Announced Date                            30 non-null     datetime64[ns]
 67  STOCK NAME                                       30 non-null     object
 68  MA                                               30 non-null     float64
dtypes: datetime64[ns](6), float64(43), int64(3), object(17)
memory usage: 16.3+ KB

(   Sr.No.  Accord Code                      Company Name BS_Year end date  \
 1       6       293601  Archean Chemical Industries Ltd.       2024-03-31
 2       8       100477                Ashok Leyland Ltd.       2024-03-31
 5      12       228465  Barbeque-Nation Hospitality Ltd.       2024-03-31
 6      14       131358         Choice International Ltd.       2024-03-31
 7      16       221842         CreditAccess Grameen Ltd.       2024-03-31

    BS_Share Capital BS_Year end date1  BS_Share Capital1  BS_Year End  \
 1           24.6794        2023-03-31            24.6106       202403
 2          293.6300        2023-03-31           293.6100       202403
 5           19.5360        2023-03-31            19.4900       202403
 6          199.3790        2023-03-31            99.5120       202403
 7          159.3800        2023-03-31           158.9100       202403

    BS_Total Debt (Long Term Plus Short Term)  \
 1                                    59.5446
 2                                 40564.3400
 5                                    39.6770
 6                                   454.0779
 7                                 21841.0100

    BS_Total Debt (Long Term Plus Short Term)1  ...  RoA Annual %  \
 1                                     21.4921  ...         15.51
 2                                  30920.4400  ...          3.67
 5                                     19.5560  ...         -1.04
 6                                    205.6597  ...          7.24
 7                                  16312.2600  ...          5.01

    Sector Return on Assets Industry Return on Assets  Piotroski Score  \
 1                     9.90                      7.88              4.0
 2                    10.64                      7.09              4.0
 5                     5.99                      3.40              2.0
 6                     2.86                      8.70              4.0
 7                     2.86                      2.51              4.0

                      sector_name            Industry Name.1  \
 1     Chemicals & Petrochemicals        Commodity Chemicals
 2  Automobiles & Auto Components        Commercial Vehicles
 5   Hotels Restaurants & Tourism                Restaurants
 6            Banking and Finance            Capital Markets
 7            Banking and Finance  Microfinance Institutions

    Latest financial result  Result Announced Date  STOCK NAME         MA
 1               2024-12-31             2025-05-02         ACI  1089755.4
 2               2024-12-31             2025-02-12    ASHOKLEY  9476276.5
 5               2024-12-31             2025-02-03    BARBEQUE   325761.3
 6               2025-03-31             2025-04-22    CHOICEIN   481436.7
 7               2024-12-31             2025-01-24   CREDITACC  3557512.5

 [5 rows x 69 columns],
 11)

In [28]:
# merged_df = pd.merge(df1, df2, how='inner', left_on='Company Name', right_on='Stock Name')
# merged_df.head()

In [29]:
df3 = pd.read_excel("C:/Users/meets/AVENTUS_FACTOR-MODEL/SIMPLE STRATEGY/L Valuation Data.xlsx")

final_merged_df = pd.merge(merged_df, df3, how='inner', left_on='Company Name', right_on='Company Name')
final_merged_df.head()

mean_value = final_merged_df['FR_Adjusted PE (x)'].mean()
std_dev = final_merged_df['FR_Adjusted PE (x)'].std()
final_merged_df['ZSCORE_PE'] = (final_merged_df['FR_Adjusted PE (x)']-mean_value) / std_dev

mean_value = final_merged_df['FR_EV/EBITDA(x)'].mean()
std_dev = final_merged_df['FR_EV/EBITDA(x)'].std()
final_merged_df['ZSCORE_EVEBITDA'] = (final_merged_df['FR_EV/EBITDA(x)']-mean_value) / std_dev

final_merged_df['ZSCORE_FINAL'] = ((1/5) * final_merged_df['ZSCORE_SHARECAPITAL']) + ((1/5) * final_merged_df['ZSCORE_DEBTGROWTH']) + ((1/5) * final_merged_df['ZSCORE_CAPEX']) + (0.20 * final_merged_df['ZSCORE_MCAP']) + (0.10 * final_merged_df['ZSCORE_PE']) + (0.10 * final_merged_df['ZSCORE_EVEBITDA'])
# final_merged_df['ZSCORE_FINAL'] = (1 * final_merged_df['ZSCORE_CAPEX'])



final_merged_df = final_merged_df[final_merged_df["ZSCORE_FINAL"]>0]

# final_merged_df['PORTFOLIO_WEIGHTS'] = final_merged_df["ZSCORE_FINAL"]/final_merged_df["ZSCORE_FINAL"].sum()

column_list = final_merged_df['Stock Code'].tolist()
# print(column_list)

final_merged_df.head()

final_merged_df.to_csv("final_s22025.csv")

In [ ]:
df = pd.read_csv("C:/Users/meets/AVENTUS_FACTOR-MODEL/SIMPLE STRATEGY/mega_dateclose_final.csv")
columns_to_keep = ['Date'] + [col for col in column_list if col in df.columns]
filtered_with_date_df = df[columns_to_keep]


filtered_with_date_df['Date'] = pd.to_datetime(filtered_with_date_df['Date'])
start_date = pd.to_datetime("2018-03-31")
end_date = pd.to_datetime("2021-04-02")
filtered_df = filtered_with_date_df[(filtered_with_date_df['Date'] >= start_date) & (filtered_with_date_df['Date'] <= end_date)]
filtered_df.head()


df_cleaned = filtered_df.dropna(how='all', subset=filtered_df.columns.difference(['Date']))
rows_removed = len(filtered_df) - len(df_cleaned)
# print("ROWS REMOVED i.e. ALL VALUES MISSING EXCEPT DATE:", rows_removed)
df_cleaned.head()


df_fully_cleaned = df_cleaned.dropna(axis=1)
final_columns = df_fully_cleaned.columns.tolist()
if 'Date' in final_columns:
    final_columns.remove('Date')
print(final_columns)
df_fully_cleaned.head()


df_fully_cleaned['Date'] = pd.to_datetime(df_fully_cleaned['Date'])
df_fully_cleaned.set_index('Date', inplace=True)
pct_change_df = df_fully_cleaned.pct_change() 
pct_change_df = pct_change_df.iloc[1:] 
pct_change_df.head()
# pct_change_df.to_csv("gptwork.csv",index=False)



pct_change_df = pct_change_df.reset_index()  # This moves 'Date' from index to a regular column
pct_change_df.head()
# pct_change_df.to_csv("data1.csv",index=False)





# pct_change_df.to_csv("deletenow.csv",index=False)
# nan_counts = pct_change_df.isna().sum()
# print(nan_counts)
# columns_without_nans = df.columns[df.isna().sum() == 0].tolist()
# print(columns_without_nans)

# pct_change_df.dropna

In [ ]:
# PORTFOLIO WT CALCULATION

final_df = final_merged_df[final_merged_df['Stock Code'].isin([name.upper() for name in final_columns])]
final_df.head()

final_df['PORTFOLIO_WEIGHTS'] = final_df["ZSCORE_FINAL"]/final_df["ZSCORE_FINAL"].sum()
final_df.head()

final_df = final_df[["Stock Code","PORTFOLIO_WEIGHTS"]]
final_df.head(20)
# final_df.to_csv("data2.csv",index=False)

In [ ]:
#DIRECT COPYPASTE - NO EDIT


# Align columns: ensure weights match the columns in the return dataframe
returns_df = pct_change_df.copy()
weights_df = final_df.set_index("Stock Code")["PORTFOLIO_WEIGHTS"]

# Ensure only common stocks are used
common_stocks = returns_df.columns.intersection(weights_df.index)
returns_matrix = returns_df[common_stocks].copy()
weights_vector = weights_df.loc[common_stocks]

# Perform matrix multiplication (dot product) for each date
returns_df["Portfolio Return"] = returns_matrix.dot(weights_vector)

# Show a few results
final_portfolio = returns_df[["Date", "Portfolio Return"]]
final_portfolio.info()

In [ ]:
#DIRECT COPYPASTE - NO EDIT

df2 = pd.read_csv("C:/Users/meets/AVENTUS_FACTOR-MODEL/SIMPLE STRATEGY/BENCHMARK/BSE500_PCTRETURNS_09-25.csv")
df2['BDP_Date'] = pd.to_datetime(df2['BDP_Date'])

final_portfolio_benchmark = pd.merge(final_portfolio, df2, how='inner', left_on='Date', right_on='BDP_Date')
final_portfolio_benchmark = final_portfolio_benchmark.drop('BDP_Date', axis=1)
final_portfolio_benchmark.set_index('Date', inplace=True)
final_portfolio_benchmark = final_portfolio_benchmark.rename(columns={'Portfolio Return':'Strategy'})
final_portfolio_benchmark.head()
# final_portfolio_benchmark.to_csv("s2l6b.csv")
# final_portfolio_benchmark.to_csv("final_portfolio_benchmarkQ.csv")

In [ ]:
import quantstats as qs

final_portfolio_benchmark.index = pd.to_datetime(final_portfolio_benchmark.index)

qs.reports.full(final_portfolio_benchmark['Strategy'],benchmark = final_portfolio_benchmark['BDP_Close'],mode="full")